MYSCALE_HOST = "msc-950b9f1f.us-east-1.aws.myscale.com" # read-only database provided by MyScale
MYSCALE_PORT = 443
MYSCALE_USER = "chatdata"
MYSCALE_PASSWORD = "myscale_rocks"
OPENAI_API_BASE = "https://api.openai.com/v1"
OPENAI_API_KEY = "<your-openai-key>"
UNSTRUCTURED_API = "<your-unstructured-io-api>" # optional if you don't upload documents
AUTH0_DOMAIN = "myscale-chatdata.us.auth0.com"            # optional if you don't user management
AUTH0_CLIENT_ID = "Y6yT2CR2RPySdyc00HpTYtJzzvaq335S"      # optiona
MODE = "dev"  # dev mode, use http connect MyScaleDB, otherwise use https.